name: Publish Maven Central

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Java
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: temurin
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      # FIXME signed JARs using github GPG key?
      - name: Publish package
        run: ./gradlew -PpublishMode=remote "-DreleasesRepoUrl=${{ env.MAVEN_REPO_URL }}" publish
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN:    ${{ secrets.GITHUB_TOKEN }}
          MAVEN_REPO_URL:  'https://oss.sonatype.org/services/local/staging/deploy/maven2/'
          MAVEN_USERNAME:  ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD:  ${{ secrets.OSSRH_PASSWORD }}
